### ISSUE TITLE
feature request:  please add "assume-yes" option or interactive option 

### ISSUE THREAD

**Issue by Dutchglory** [openSUSE/opi#142] opened 2023-07-22 07:51 UTC
OS INFORMATION
~~~~~~~~~~~~~~~~~~
Operating System: openSUSE Leap 15.5
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 5.14.21-150500.55.7-default (64-bit)
Graphics Platform: X11
Processors: 2 × Intel® Core™2 CPU 6700 @ 2.66GHz
Memory: 5.7 GiB of RAM
Graphics Processor: GeForce GT 610/PCIe/SSE2


feature request:   please add "assume-yes" option or interactive option to install packages automatically ...

André

**Comment by nobkd** [comment] 2023-07-22 21:56
Duplicate of #117

**Closed** 2023-07-26 13:35 UTC
